export const POST_APPOINTMENTS="POST_APPOINTMENTS";
export const USER_LOADING="USER_LOADING";
export const GET_APPOINTMENTS="GET_APPOINTMENTS";
export const DELETE_APPOINTMENT="DELETE_APPOINTMENT";
export const AUTH_ERRORS="AUTH_ERRORS";
