export const  GET_MEDICALFILES="GET_MEDICALFILES";
export const POST_MEDICALFILES="POST_MEDICALFILES";
export const AUTH_ERRORS="AUTH_ERRORS";
export const USER_LOADING="USER_LOADING";
export const GET_AUTH_USER="GET_AUTH_USER";
export const DELETE_MEDICALFILE="DELETE_MEDICALFILE";
export const EDIT_MEDICALFILES="EDIT_MEDICALFILES";